from pathlib import Path

# Project root directory (two levels above: src/core -> project root)
ROOT_DIR = Path(__file__).resolve().parents[2]

# Core folders
DATA_DIR = ROOT_DIR / "data"
EXTERNAL_DIR = ROOT_DIR / "_external"
ARTIFACTS_DIR = ROOT_DIR / "artifacts"
CHECKPOINTS_DIR = ARTIFACTS_DIR / "checkpoints"
REPORTS_DIR = ARTIFACTS_DIR / "reports"
LOGS_DIR = ARTIFACTS_DIR / "logs"
MT_BENCH_DIR = DATA_DIR / "mt_bench"
MMLU_DIR = DATA_DIR / "mmlu"

CHECKPOINTS_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)
LOGS_DIR.mkdir(parents=True, exist_ok=True)

# Artifacts generated by training / preprocessing
CIDT_CHECKPOINT = CHECKPOINTS_DIR / "cidt_final.pt"
HB_BENIGN = CHECKPOINTS_DIR / "Hb_benign_layer15.pt"
FITD_TRAIN_DATA = ROOT_DIR / "fitd_train_data.json"
MIXED_TRAIN_DATA = ROOT_DIR / "mixed_train_data.json"
BENCHMARK_REPORT = REPORTS_DIR / "full_benchmark_report.json"
BENCHMARK_REPORT_BASELINE = REPORTS_DIR / "full_benchmark_report_baseline.json"
TEST_LOG = LOGS_DIR / "test_log.log"

# Data files used by benchmarking and preprocessing
ADV_BENCH_CSV = DATA_DIR / "advbench.csv"
HARMFUL_BEHAVIORS_CSV = DATA_DIR / "harmful_behaviors.csv"
JAILBREAKBENCH_CSV = DATA_DIR / "jailbreakbench.csv"
MALICIOUSINSTRUCT_CSV = DATA_DIR / "maliciousinstruct.csv"
MULTIBREAK_JSONL = DATA_DIR / "multibreak.jsonl"
CRESCENDO_JSON = DATA_DIR / "crescendo.json"
GSM8K_JSONL = DATA_DIR / "gsm8k_test.jsonl"
HUMANEVAL_JSONL = DATA_DIR / "humaneval.jsonl"
MT_BENCH_JSONL = MT_BENCH_DIR / "question.jsonl"

SAE_BENIGN_PROMPTS_JSON = DATA_DIR / "sae_benign_prompts.json"
SAE_MALICIOUS_PROMPTS_JSON = DATA_DIR / "sae_malicious_prompts.json"
VERIFIED_REFUSAL_FEATURES_PT = DATA_DIR / "verified_refusal_features.pt"

# Optional local mirrors from other workspaces (used as fallback only)
LOCAL_MIRROR_ADV_BENCH = Path("/home/asus/ycy/Foot-in-the-door-Jailbreak/data/advbench.csv")
LOCAL_MIRROR_JBB = Path("/home/asus/ycy/Foot-in-the-door-Jailbreak/data/jailbreakbench.csv")
LOCAL_MIRROR_MT_BENCH = Path("/home/asus/ycy/phase1_exp/data/raw/mt_bench_question.jsonl")
LOCAL_MIRROR_CRESCENDO = Path("/home/asus/ycy/phase1_exp/data/processed/multiturn_harmful_crescendo.jsonl")
LOCAL_MIRROR_MULTIBREAK = Path("/home/asus/ycy/phase1_exp/data/processed/multiturn_harmful_multibreak.jsonl")
LOCAL_MIRROR_GSM8K = Path("/home/asus/lyl/fed-sb/fed_sb/data/math_eval/gsm8k_test.jsonl")

EXTERNAL_CRESCENDO_PROMPTS = EXTERNAL_DIR / "crescendoattacker" / "crescendo_prompts.json"
